version: '3'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data_bot:/var/lib/postgresql/data
    ports:
      - ${DOCKER_COMPOSE_POSTGRES_PORTS}

volumes:
  postgres_data_bot:
