version: '3'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres_data_bot:/var/lib/postgresql/data
    ports:
      - ${DOCKER_COMPOSE_POSTGRES_PORTS}
  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbit-bot
    restart: always
    container_name: rabbitmq
    ports:
      - ${RABBITMQ_PORTS}
      - ${RABBITMQ_MANAGEMENT_PORTS}
    volumes:
      - rabbitmq_data_bot:/var/lib/rabbitmq

volumes:
  postgres_data_bot:
  rabbitmq_data_bot:
