@startuml
hide footbox

title Create or delete subscription

actor User as user
participant Bot as bot
database DB as db

activate user
activate bot
user -> bot: /new, /delete - create or delete subscription
activate db
bot -> db
db --> bot
bot --> user: subscription is created or deleted
deactivate db
@enduml
